export const liveUpdateUsersDeposit = [
    { id: 1, name: 'Alice Dupont', country: 'fr', countryFullName: 'France', value: 4890 },
    { id: 2, name: 'John Smith', country: 'us', countryFullName: 'United States', value: 9342 },
    { id: 3, name: 'Liam O Connor', country: 'ie', countryFullName: 'Ireland', value: 3044 },
    { id: 4, name: 'Yuki Tanaka', country: 'jp', countryFullName: 'Japan', value: 7821 },
    { id: 5, name: 'Carlos Ruiz', country: 'mx', countryFullName: 'Mexico', value: 2650 },
    { id: 6, name: 'Sara Ahmed', country: 'eg', countryFullName: 'Egypt', value: 8410 },
    { id: 7, name: 'David Müller', country: 'de', countryFullName: 'Germany', value: 6012 },
    { id: 8, name: 'Fatima Al-Farsi', country: 'ae', countryFullName: 'United Arab Emirates', value: 4553 },
    { id: 9, name: 'Ivan Petrov', country: 'ru', countryFullName: 'Russia', value: 7310 },
    { id: 10, name: 'Thabo Mokoena', country: 'za', countryFullName: 'South Africa', value: 5203 },
    { id: 11, name: 'Emily Brown', country: 'au', countryFullName: 'Australia', value: 3890 },
    { id: 12, name: 'Chen Wei', country: 'cn', countryFullName: 'China', value: 9188 },
    { id: 13, name: 'Noah van Dijk', country: 'nl', countryFullName: 'Netherlands', value: 4760 },
    { id: 14, name: 'Isabella Rossi', country: 'it', countryFullName: 'Italy', value: 6311 },
    { id: 15, name: 'Lucas Martin', country: 'ar', countryFullName: 'Argentina', value: 7095 },
    { id: 16, name: 'Amira Ben Ali', country: 'tn', countryFullName: 'Tunisia', value: 3342 },
    { id: 18, name: 'Jorge Mendes', country: 'pt', countryFullName: 'Portugal', value: 8123 },
    { id: 19, name: 'Anna Kowalska', country: 'pl', countryFullName: 'Poland', value: 4080 },
    { id: 20, name: 'Omar Farouk', country: 'ng', countryFullName: 'Nigeria', value: 6122 },
    { id: 21, name: 'Hannah Müller', country: 'de', countryFullName: 'Germany', value: 5900 },
    { id: 22, name: 'Andrés Gómez', country: 'co', countryFullName: 'Colombia', value: 6640 },
    { id: 23, name: 'Sophie Dubois', country: 'be', countryFullName: 'Belgium', value: 3812 },
    { id: 24, name: 'Aarav Patel', country: 'in', countryFullName: 'India', value: 7491 },
    { id: 25, name: 'Kim Min-jun', country: 'kr', countryFullName: 'South Korea', value: 8322 },
    { id: 26, name: 'Mia Jensen', country: 'dk', countryFullName: 'Denmark', value: 4109 },
    { id: 27, name: 'Lucas Silva', country: 'br', countryFullName: 'Brazil', value: 6700 },
    { id: 28, name: 'Elena Popa', country: 'ro', countryFullName: 'Romania', value: 5234 },
    { id: 29, name: 'Samantha Lee', country: 'sg', countryFullName: 'Singapore', value: 5588 },
    { id: 30, name: 'Mikhail Ivanov', country: 'ru', countryFullName: 'Russia', value: 8001 },
    { id: 31, name: 'Nina Johansson', country: 'se', countryFullName: 'Sweden', value: 4671 },
    { id: 32, name: 'George Brown', country: 'gb', countryFullName: 'United Kingdom', value: 7770 },
    { id: 33, name: 'Juan Carlos', country: 'es', countryFullName: 'Spain', value: 7215 },
    { id: 34, name: 'Zanele Dlamini', country: 'za', countryFullName: 'South Africa', value: 5566 },
    { id: 35, name: 'Nguyen Van A', country: 'vn', countryFullName: 'Vietnam', value: 6884 },
    { id: 36, name: 'Ali Reza', country: 'ir', countryFullName: 'Iran', value: 4190 },
    { id: 37, name: 'Mateo Fernández', country: 'uy', countryFullName: 'Uruguay', value: 4910 },
    { id: 38, name: 'Laura Schmid', country: 'ch', countryFullName: 'Switzerland', value: 5882 },
    { id: 39, name: 'Andrei Stoica', country: 'ro', countryFullName: 'Romania', value: 3010 },
    { id: 40, name: 'Emma Thompson', country: 'ca', countryFullName: 'Canada', value: 8510 },
    { id: 41, name: 'Daniel Kim', country: 'kr', countryFullName: 'South Korea', value: 6320 },
    { id: 42, name: 'Lara Haddad', country: 'lb', countryFullName: 'Lebanon', value: 3650 },
    { id: 43, name: 'Arjun Mehta', country: 'in', countryFullName: 'India', value: 9241 },
    { id: 44, name: 'Mohammed Al Said', country: 'sa', countryFullName: 'Saudi Arabia', value: 7143 },
    { id: 45, name: 'Sophia Müller', country: 'at', countryFullName: 'Austria', value: 5912 },
    { id: 46, name: 'Jakub Nowak', country: 'pl', countryFullName: 'Poland', value: 4125 },
    { id: 47, name: 'Mehdi Bouazizi', country: 'dz', countryFullName: 'Algeria', value: 7284 },
    { id: 48, name: 'Anastasia Romanova', country: 'ru', countryFullName: 'Russia', value: 8740 },
    { id: 49, name: 'Pedro Lima', country: 'br', countryFullName: 'Brazil', value: 4021 },
    { id: 50, name: 'Greta Novak', country: 'cz', countryFullName: 'Czech Republic', value: 3632 },
    { id: 51, name: 'Tariq Jaber', country: 'jo', countryFullName: 'Jordan', value: 6480 },
    { id: 52, name: 'María López', country: 'es', countryFullName: 'Spain', value: 7730 },
    { id: 53, name: 'João Santos', country: 'pt', countryFullName: 'Portugal', value: 8312 },
    { id: 54, name: 'Olga Ivanova', country: 'ua', countryFullName: 'Ukraine', value: 7152 },
    { id: 55, name: 'Kofi Mensah', country: 'gh', countryFullName: 'Ghana', value: 5052 },
    { id: 56, name: 'Siti Nurhaliza', country: 'my', countryFullName: 'Malaysia', value: 3880 },
    { id: 57, name: 'Anna Berg', country: 'no', countryFullName: 'Norway', value: 6370 },
    { id: 58, name: 'Ahmed Ali', country: 'sd', countryFullName: 'Sudan', value: 4295 },
    { id: 59, name: 'Zara Khan', country: 'pk', countryFullName: 'Pakistan', value: 7410 },
    { id: 60, name: 'Anders Svensson', country: 'se', countryFullName: 'Sweden', value: 6720 },
    { id: 61, name: 'Tuan Nguyen', country: 'vn', countryFullName: 'Vietnam', value: 8012 },
    { id: 62, name: 'Mina Okafor', country: 'ng', countryFullName: 'Nigeria', value: 5675 },
    { id: 63, name: 'Lukas Novak', country: 'cz', countryFullName: 'Czech Republic', value: 3150 },
    { id: 64, name: 'Rania El Bakry', country: 'ma', countryFullName: 'Morocco', value: 6988 },
    { id: 65, name: 'Ivan Dimitrov', country: 'bg', countryFullName: 'Bulgaria', value: 4690 },
    { id: 66, name: 'Amina Yusuf', country: 'ke', countryFullName: 'Kenya', value: 4870 },
    { id: 67, name: 'Hassan Nasser', country: 'qa', countryFullName: 'Qatar', value: 7980 },
    { id: 68, name: 'Adriana Popescu', country: 'ro', countryFullName: 'Romania', value: 4210 },
    { id: 69, name: 'Luis Herrera', country: 'cl', countryFullName: 'Chile', value: 5803 },
    { id: 70, name: 'Jin Soo', country: 'kr', countryFullName: 'South Korea', value: 7633 }
  ];
  


 export  const liveUpdateUsersWithdrawal = [
    { id: 1, name: 'Elena Garcia', country: 'es', countryFullName: 'Spain', value: 4532.15 },
    { id: 2, name: 'Mark Johnson', country: 'us', countryFullName: 'United States', value: 7291.84 },
    { id: 3, name: 'Sofia Petrova', country: 'bg', countryFullName: 'Bulgaria', value: 3187.62 },
    { id: 4, name: 'Jinwoo Kim', country: 'kr', countryFullName: 'South Korea', value: 8420.47 },
    { id: 5, name: 'Amira Hassan', country: 'eg', countryFullName: 'Egypt', value: 2743.28 },
    { id: 6, name: 'Nikolai Ivanov', country: 'ru', countryFullName: 'Russia', value: 6892.55 },
    { id: 7, name: 'Maya Singh', country: 'in', countryFullName: 'India', value: 5010.33 },
    { id: 8, name: 'Liam O’Reilly', country: 'ie', countryFullName: 'Ireland', value: 7321.90 },
    { id: 9, name: 'Hannah Schmidt', country: 'de', countryFullName: 'Germany', value: 6127.18 },
    { id: 10, name: 'Carlos Fernandez', country: 'mx', countryFullName: 'Mexico', value: 3894.75 },
    { id: 11, name: 'Fatima Al-Sayed', country: 'ae', countryFullName: 'United Arab Emirates', value: 5342.29 },
    { id: 12, name: 'Noah Andersson', country: 'se', countryFullName: 'Sweden', value: 4789.66 },
    { id: 13, name: 'Laura Bennett', country: 'gb', countryFullName: 'United Kingdom', value: 6601.12 },
    { id: 14, name: 'Pedro Alvarez', country: 'ar', countryFullName: 'Argentina', value: 7234.57 },
    { id: 15, name: 'Olga Smirnova', country: 'ru', countryFullName: 'Russia', value: 3498.83 },
    { id: 16, name: 'Emma Jensen', country: 'dk', countryFullName: 'Denmark', value: 5921.44 },
    { id: 17, name: 'Mohamed Ali', country: 'sd', countryFullName: 'Sudan', value: 4783.26 },
    { id: 18, name: 'Sofia Rossi', country: 'it', countryFullName: 'Italy', value: 6280.19 },
    { id: 19, name: 'Lucas Martin', country: 'br', countryFullName: 'Brazil', value: 7839.04 },
    { id: 20, name: 'Anya Petrov', country: 'bg', countryFullName: 'Bulgaria', value: 4102.51 },
    { id: 21, name: 'Sara Lindberg', country: 'se', countryFullName: 'Sweden', value: 5241.78 },
    { id: 22, name: 'Jack Wilson', country: 'au', countryFullName: 'Australia', value: 3678.99 },
    { id: 23, name: 'Isabelle Dubois', country: 'fr', countryFullName: 'France', value: 4182.34 },
    { id: 24, name: 'Tariq Jaber', country: 'jo', countryFullName: 'Jordan', value: 5893.43 },
    { id: 25, name: 'Nina Novak', country: 'cz', countryFullName: 'Czech Republic', value: 4768.21 },
    { id: 26, name: 'Ahmed Hassan', country: 'eg', countryFullName: 'Egypt', value: 6190.56 },
    { id: 27, name: 'Maria Silva', country: 'pt', countryFullName: 'Portugal', value: 4332.87 },
    { id: 28, name: 'Omar Nasser', country: 'qa', countryFullName: 'Qatar', value: 7502.68 },
    { id: 29, name: 'Lila Nguyen', country: 'vn', countryFullName: 'Vietnam', value: 3829.95 },
    { id: 30, name: 'Felix Müller', country: 'ch', countryFullName: 'Switzerland', value: 6117.52 }
  ];
  